version: '2.3'
services:

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - /home/rkawamori/Asobi/crypto_deriv:/home/
    env_file:
      - .env
    environment:
      TZ: Asia/Tokyo
      PYTHONPATH: /home/
    networks:
      - app-net
    tty: true

  jupyter:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - /home/rkawamori/Asobi/crypto_deriv:/home/
    env_file:
      - .env
    environment:
      JUPYTER_PATH: /home/
      TZ: Asia/Tokyo
      PYTHONPATH: /home/
    networks:
      - app-net
    ports:
      - 8890:8890
    tty: true

  market_monitor:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - /home/rkawamori/Asobi/crypto_deriv:/home/
    env_file:
      - .env
    environment:
      JUPYTER_PATH: /home/
      TZ: Asia/Tokyo
      PYTHONPATH: /home/
    networks:
      - app-net
    ports:
      - 8000:8000
    tty: true


networks:
  app-net:
    driver: bridge